print("hello world")
print("My name is Kush Oza")
print("I am a software engineer")
print("I love coding")
print("I am learning Python")
print("I am excited to build projects")
print("I am looking forward to learning more about Python")
print("I am about to see some merge conflicts")
print("I am going to resolve them")
print("I am going to do it")
print("I am going to nike it")
